# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets exec'd

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
dialogBox = RsgDialog(title='PSCT', kernelModule='TEST_1div8', kernelFunction='create_model_for_psct', includeApplyBtn=False, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=thisDir)

RsgTabBook(name='TabBook', p='DialogBox', layout='0')
RsgTabItem(name='TabItem_1', p='TabBook', text='Geometry')


RsgTextField(p = 'TabItem_1', fieldType='String', ncols=12, labelText='Name', keyword='nameOfModel', default='Model-1')
RsgIcon(p = 'TabItem_1', fileName=r'PSCT_Image.png')
RsgTextField(p = 'TabItem_1', fieldType='Float', ncols=12, labelText='Width of compression', keyword='widthOfCompression', default='0.015')
RsgTextField(p = 'TabItem_1', fieldType='Float', ncols=12, labelText='High of compression', keyword='highOfCompression', default='0.01')
RsgTextField(p = 'TabItem_1', fieldType='Float', ncols=12, labelText='Depth of compression', keyword='depthOfCompression', default='0.0550')
RsgTextField(p = 'TabItem_1', fieldType='Float', ncols=12, labelText='Width of sample', keyword='widthOfSample', default='0.07')
RsgTextField(p = 'TabItem_1', fieldType='Float', ncols=12, labelText='High of sample', keyword='highOfSample', default='0.005')
RsgTextField(p = 'TabItem_1', fieldType='Float', ncols=12, labelText='Depth of sample', keyword='depthOfSample', default='0.05')

RsgTabItem(name='TabItem_2', p='TabBook', text='Properties')

RsgTextField(p = 'TabItem_2', fieldType='Float', ncols=12, labelText='Mass density', keyword='density', default='2700')
RsgTable(p = 'TabItem_2', numRows=1, columnData=[('Young`s module', 'Float', 200), ('Poisson`s ratio', 'Float', 200)], showRowNumbers=True, showGrids=True, keyword='elasticParams', popupFlags='AFXTable.POPUP_COPY|AFXTable.POPUP_PASTE')
RsgTable(p = 'TabItem_2', numRows=5, columnData=[('Stress', 'Float', 150), ('Strain', 'Float', 150), ('Rate', 'Float', 150)], showRowNumbers=True, showGrids=True, keyword='plasticParams', popupFlags='AFXTable.POPUP_COPY|AFXTable.POPUP_PASTE|AFXTable.POPUP_INSERT_ROW|AFXTable.POPUP_DELETE_ROW|AFXTable.POPUP_CLEAR_CONTENTS')

RsgTabItem(name='TabItem_3', p='TabBook', text='Mesh')
RsgTextField(p = 'TabItem_3', fieldType='Float', ncols=12, labelText='Size of mesh', keyword='sizeOfMesh', default='0.0005')

RsgTabItem(name='TabItem_4', p='TabBook', text='Boundary conditions')
RsgTextField(p = 'TabItem_4', fieldType='Float', ncols=12, labelText='Friction', keyword='friction', default='0.2')
RsgTable(p = 'TabItem_4', numRows=5, columnData=[('Time/freq', 'Float', 200), ('Amplitude', 'Float', 200)], showRowNumbers=True, showGrids=True, keyword='amplitudeAndTime', popupFlags='AFXTable.POPUP_COPY|AFXTable.POPUP_PASTE|AFXTable.POPUP_INSERT_ROW|AFXTable.POPUP_DELETE_ROW|AFXTable.POPUP_CLEAR_CONTENTS')
RsgTextField(p = 'TabItem_4', fieldType='Float', ncols=12, labelText='Speed', keyword='speed', default='1')

RsgTabItem(name='TabItem_5', p='TabBook', text='Step')
RsgTextField(p = 'TabItem_5', fieldType='Float', ncols=12, labelText='initialInc', keyword='initialIncrement', default='30')
RsgTextField(p = 'TabItem_5', fieldType='Float', ncols=12, labelText='maxInc', keyword='maxIncrement', default='30')
RsgTextField(p = 'TabItem_5', fieldType='Integer', ncols=12, labelText='maxNumInc', keyword='maxNumIncrement', default='99999999')
RsgTextField(p = 'TabItem_5', fieldType='Float', ncols=12, labelText='minInc', keyword='minIncrement', default='0.0003')
RsgTextField(p = 'TabItem_5', fieldType='Float', ncols=12, labelText='timePeriod', keyword='time', default='30')

dialogBox.show()